### ISSUE TITLE
compiler/makeprg isn't being set correctly

### ISSUE THREAD

**Issue by jasonkarns** [aliou/bats.vim#7]
The filetype is being detected correctly, but executing `:Make` (or :Dispatch from https://github.com/tpope/vim-dispatch) is still attempting to execute `make`, not `bats`.

`:set makeprg` -> ` makeprg=make`

**Comment by aliou** [comment]
Indeed, I may have forgotten to do something in the ftplugin. I'll check.

**Comment by aliou** [comment]
Yup, forgot to enable the compiler after the filetype detection. Released [v0.5.0](https://github.com/aliou/bats.vim/releases/tag/v0.5.0) with this fix.

I also noticed that it tried to run bats without any arguments, so I [made the `makeprg` run the bats on the current file](https://github.com/aliou/bats.vim/commit/61c620c542ff9506f75c553019073945c29e50fc). Let me know if this works correctly for you. Cheers!

**Comment by jasonkarns** [comment]
Works great!  Thanks so much!

Quick side question since I haven't looked closely... should bats be put into TAP mode with the `-t` flag or no? Not sure which format your output parsing is expecting...

**Comment by aliou** [comment]
I haven't really thought about it but it makes sense to at least have the TAP mode configurable. I'll take a look at how other compiler handle this and will let you know.
Regarding the output parsing, the current one doesn't really work 😭 (see #4)

**Comment by jasonkarns** [comment]
🤷‍♂️ regardless, the current implementation works to get basic info to quickfix window so 🎉
